### ISSUE TITLE
Update multipass environment to work with the latest changes and mongodb

### ISSUE THREAD

**Issue by nadzyah** [canonical/testflinger#26]
The [testflinger.yaml](https://github.com/canonical/testflinger/blob/main/devel/testflinger.yaml) contains outdated information about Redis database, which we don’t use anymore. It needs to be updated, since we want to be able to run testflinger instance with MongoDB in multipass

**Comment by plars** [comment]
Where are you seeing this? I believe the example .conf file was fixed in commit da37d30aab9734844432d93e3a93ad818e8aae7e

**Comment by nadzyah** [comment]
> Where are you seeing this? I believe the example .conf file was fixed in commit [da37d30](https://github.com/canonical/testflinger/commit/da37d30aab9734844432d93e3a93ad818e8aae7e)

@plars check lines [69-70](https://github.com/canonical/testflinger/blob/main/devel/testflinger.yaml#L69-L70) and [125](https://github.com/canonical/testflinger/blob/main/devel/testflinger.yaml#L125)

**Comment by plars** [comment]
Ah, the multipass stuff, I thought you were just talking about the example config file. Yes we need to update a LOT of stuff with that but I'm waiting on some other things to settle down first, since there seems to be a lot of debate over env vars and things like that. Let's change the title of this a bit so it's more clear.

**Comment by nadzyah** [comment]
> Ah, the multipass stuff, I thought you were just talking about the example config file. Yes we need to update a LOT of stuff with that but I'm waiting on some other things to settle down first, since there seems to be a lot of debate over env vars and things like that. Let's change the title of this a bit so it's more clear.

Thank you!
