### ISSUE TITLE
Using media parameter egual usb with muxpi agent can lead to job failure

### ISSUE THREAD

**Issue by rmartin013** [canonical/testflinger#296]
When "media: usb" is used for a TF job with a device connected with zapper and a typecmux, the job can fail if there is no sdwire installed on the zapper.

**Comment by rmartin013** [comment]
Ex: 
* http://10.102.156.15:8080/job/partner-engineering/job/riverside/job/riverside-jetson-orin-nano-cdimage-daily-public/115/console 
* http://10.102.156.15:8080/job/partner-engineering/job/riverside/job/riverside-igx-orin-cdimage-daily/221/console

**Comment by plars** [comment]
Thanks for the fix!
